export const TAMBAH_BARANG = "TAMBAH_BARANG";
export const HAPUS_BARANG = "HAPUS_BARANG";
export const TAMBAH_KUANTITAS = "TAMBAH_KUANTITAS";
export const KURANGI_KUANTITAS = "KURANGI_KUANTITAS";
export const BERSIHKAN_KERANJANG = "BERSIHKAN_KERANJANG";